In [30]:
!pip install ir_datasets
!pip install rank_bm25
!pip install sentence_transformers

In [31]:
from tqdm import tqdm
import json
import ir_datasets
import os
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
from rank_bm25 import BM25Okapi
from transformers import pipeline
import torch
from huggingface_hub import login

api_key = "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"
login(token=api_key)

# Check GPU availability
def get_device():
    if torch.cuda.is_available():
        device = "cuda"
        gpu_properties = torch.cuda.get_device_properties(torch.cuda.current_device())
        print(f"Using GPU: {gpu_properties.name}")
        print(f"CUDA Cores: {gpu_properties.multi_processor_count}")
        print(f"Total Memory: {gpu_properties.total_memory / 1e9:.2f} GB")
        print(f"Compute Capability: {gpu_properties.major}.{gpu_properties.minor}")
    else:
        device = "cpu"
        print("Using CPU")
    return device

device = get_device()


Using GPU: Tesla T4
CUDA Cores: 40
Total Memory: 15.84 GB
Compute Capability: 7.5


# Section 1: Dataset loading and preparation

In [32]:
# Load dataset
print("Loading the trec covid dataset...")
dataset = ir_datasets.load("cord19/trec-covid")

# Prepare documents and queries
print("Preparing documents and queries...")
all_docs = [{"doc_id": doc.doc_id, "abstract": doc.abstract} for doc in dataset.docs_iter()]
all_queries = [{"query_id": query.query_id, "title": query.title} for query in dataset.queries_iter()]

# Print dataset size information
print(f"Summary: {len(all_docs)} documents and {len(all_queries)} queries are available in the dataset.")

tokenized_docs = [doc['abstract'].split() for doc in all_docs]
qrels = dataset.qrels

Loading the trec covid dataset...
Preparing documents and queries...
Summary: 192509 documents and 50 queries are available in the dataset.


# Section 2: Embeddings generation

In [33]:
# Load or generate embeddings
def generate_embeddings():
    if os.path.exists("trec_covid_doc_embeddings.csv") and os.path.exists("trec_covid_query_embeddings.csv"):
        print("Loading precomputed embeddings...")
        doc_embeddings = pd.read_csv("trec_covid_doc_embeddings.csv").values
        query_embeddings = pd.read_csv("trec_covid_query_embeddings.csv").values
    else:
        print("No precomputed embeddings found.")
        print("Generating new embeddings using SentenceTransformer model 'all-MiniLM-L6-v2'.")
        model = SentenceTransformer("all-MiniLM-L6-v2", device=device)
        doc_embeddings = model.encode(all_docs, batch_size=32, show_progress_bar=True)
        query_embeddings = model.encode(all_queries, batch_size=32, show_progress_bar=True)

        # Save embeddings for future use
        pd.DataFrame(doc_embeddings).to_csv("trec_covid_doc_embeddings.csv", index=False)
        pd.DataFrame(query_embeddings).to_csv("trec_covid_query_embeddings.csv", index=False)

    return doc_embeddings, query_embeddings

doc_embeddings, query_embeddings = generate_embeddings()

Loading precomputed embeddings...


# Section 3: Retrieval implementation

### Evaluation metrics
The following functions are used to evaluate the quality of document retrieval methods based on the ranked list of documents returned for a given query.

In [54]:
def dcg_at_k(scores, k):
    """Calculates the Discounted Cumulative Gain (DCG) at rank position k."""
    if not len(scores) or k <= 0:  # Handle empty input or invalid k
        return 0.0
    # Select top-k scores for evaluation
    scores = np.array(scores)[:k]
    # Calculate the discounts for each position in the ranking (logarithmic scaling)
    discounts = np.log2(np.arange(2, len(scores) + 2))
    # Return the sum of the discounted cumulative gains
    return np.sum(scores / discounts)


def ndcg_at_k(retrieved_scores, ideal_scores, k):
    """Computes the Normalized Discounted Cumulative Gain (nDCG) at rank k."""
    if not retrieved_scores.any() or not len(ideal_scores) or k <= 0:
        return 0.0
    # Calculate the DCG of the retrieved documents
    dcg = dcg_at_k(retrieved_scores, k)
    # Calculate the ideal DCG by sorting the ideal scores in descending order
    idcg = dcg_at_k(sorted(ideal_scores, reverse=True), k)
    # Return the normalized DCG value
    return dcg / idcg if idcg > 0 else 0.0


def recall_at_k(retrieved_docs, relevant_docs, k):
    """
    Calcola il Recall fino alla posizione k.
    """
    if not len(relevant_docs) or k <= 0:
        return 0.0

    # Seleziona i documenti recuperati nei top-k
    retrieved_at_k = set(retrieved_docs[:k])

    # Converti i valori in interi e considera solo quelli rilevanti
    '''
    try:
        relevant_set = set(idx for idx, rel in enumerate(map(int, relevant_docs)) if rel > 0)
    except ValueError as e:
        raise ValueError(f"Errore nella conversione dei rilevanti: {e}")

    # Calcola il recall
    return len(retrieved_at_k & relevant_set) / len(relevant_set) if len(relevant_set) > 0 else 0.0
    '''


def calculate_average_metrics(metrics, k=5):
    average_metrics = {}

    for method, method_metrics in metrics.items():
        # Estrai i valori delle metriche specifiche per il metodo
        ndcg_values = [m[f"ndcg@{k}"] for m in method_metrics]
        dcg_values = [m[f"dcg@{k}"] for m in method_metrics]
        recall_values = [m[f"recall@{k}"] for m in method_metrics]

        # Calcola le medie
        avg_ndcg = np.mean(ndcg_values)
        avg_dcg = np.mean(dcg_values)
        avg_recall = np.mean(recall_values)

        # Salva le metriche calcolate
        average_metrics[method] = {
            f"ndcg@{k}": avg_ndcg,
            f"dcg@{k}": avg_dcg,
            f"recall@{k}": avg_recall,
        }

    return average_metrics

### Document Retrieval Methods

1. **BM25 Sparse Retrieval**:
   - The **BM25 algorithm** is used to perform sparse retrieval on tokenized documents by calculating a relevance score for each document based on the query. It then returns the indices and relevance scores of the top-k most relevant documents.

2. **Dense Retrieval**:
   - **Dense retrieval** is performed by calculating the cosine similarity between the query embedding and the document embeddings. The top-k documents with the highest similarity scores are returned.

3. **Rank Fusion Retrieval**:
   - Results from both **BM25** and **dense retrieval** are combined using a **rank fusion** technique. Scores from both methods are normalized, weighted by a parameter `alpha`, and the top-k documents are returned based on the combined scores.

4. **Cascading Retrieval**:
   - Initially, a set of documents is retrieved using **BM25**. These documents are then re-ranked using dense retrieval, with a similarity threshold applied to filter documents. The top-k documents are returned based on the final ranking.

In [49]:
# BM25 Sparse Retrieval
def bm25_retrieve(query, bm25, top_k=5):
    """
    Perform sparse retrieval using BM25 on the tokenized documents.
    Returns the indices and scores of the top-k documents.
    """
    tokenized_query = query.split()                                             # Tokenize the query into words
    scores = bm25.get_scores(tokenized_query)                                   # Get BM25 scores for all documents
    top_k_indices = np.argsort(scores)[-top_k:][::-1]                           # Get indices of top-k documents based on BM25 score
    return top_k_indices, scores[top_k_indices]

# Dense Retrieval
def dense_retrieve(query_embedding, doc_embeddings, top_k=5):
    """
    Perform dense retrieval using cosine similarity between query and document embeddings.
    Returns the indices and similarities of the top-k documents.
    """
    similarities = cosine_similarity([query_embedding], doc_embeddings)[0]      # Compute cosine similarity
    top_k_indices = np.argsort(similarities)[-top_k:][::-1]                     # Get top-k indices based on similarity
    return top_k_indices, similarities[top_k_indices]

# Rank Fusion Retrieval
def fusion_retrieve(dense_query_embedding, doc_embeddings, query, top_k=5, alpha=0.5):
    """
    Implementa il rank fusion riutilizzando le funzioni esistenti di retrieval.
    """

    # Perform BM25 retrieval and dense retrieval
    sparse_indices, sparse_scores = bm25_retrieve(query, bm25, top_k=len(doc_embeddings))
    dense_indices, dense_scores = dense_retrieve(dense_query_embedding, doc_embeddings, top_k=len(doc_embeddings))

    # Initialize score arrays
    all_sparse_scores = np.zeros(len(doc_embeddings))
    all_dense_scores = np.zeros(len(doc_embeddings))

    # Fill score arrays with BM25 and dense scores
    all_sparse_scores[sparse_indices] = sparse_scores
    all_dense_scores[dense_indices] = dense_scores

    # Normalize scores
    all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
    all_dense_scores = (all_dense_scores - all_dense_scores.min()) / (all_dense_scores.max() - all_dense_scores.min())

    # Combine scores using the alpha parameter
    combined_scores = alpha * all_dense_scores + (1 - alpha) * all_sparse_scores

    # Retrieve the top-k results based on combined scores
    top_k_indices = np.argsort(combined_scores)[-top_k:][::-1]
    return top_k_indices, combined_scores[top_k_indices]

# Cascading Retrieval
def cascade_retrieve(dense_query_embedding, doc_embeddings, query, initial_k=100, final_k=5, dense_threshold=0.7):
    """
    Perform cascading retrieval: sparse retrieval followed by dense re-ranking.
    Filters documents based on a similarity threshold and returns the top-k results.
    """
    # Stage 1: BM25 to get initial candidates
    initial_indices, _ = bm25_retrieve(query, bm25, top_k=initial_k)

    # Stage 2: Dense re-ranking of candidate documents
    candidate_embeddings = doc_embeddings[initial_indices]
    _, dense_scores = dense_retrieve(dense_query_embedding, candidate_embeddings, top_k=len(initial_indices))

    # Filter candidates by similarity threshold
    qualified_mask = dense_scores >= dense_threshold
    if np.sum(qualified_mask) >= final_k:
        # Select top-k qualified candidates
        qualified_indices = np.where(qualified_mask)[0]
        top_indices = qualified_indices[np.argsort(dense_scores[qualified_indices])[-final_k:][::-1]]
    else:
        # If there are not enough qualified candidates, select top-k by overall scores
        top_indices = np.argsort(dense_scores)[-final_k:][::-1]

    # Map filtered indices to original document IDs
    final_indices = initial_indices[top_indices]
    final_scores = dense_scores[top_indices]

    return final_indices, final_scores



In [50]:
# Initialize BM25 model
print("Initializing BM25 model.")
bm25 = BM25Okapi(tokenized_docs)

Initializing BM25 model.


This section of code performs several retrieval experiments using the four different Document Retrieval Methods described earlier.

In [55]:
# Run retrieval experiments
def run_retrieval_experiments():
    """
    Execute sparse, dense, rank fusion, and cascading retrieval for all queries.
    Save the results to a JSON file for further analysis.
    """
    results = {
        "sparse": [],
        "dense": [],
        "rank_fusion": [],
        "cascade": []
    }
    metrics = {
        "sparse": [],
        "dense": [],
        "rank_fusion": [],
        "cascade": []
    }

    print("Running retrieval experiments on all queries.")

    # Iterate over each query and its embedding
    for query, query_embedding in tqdm(zip(all_queries, query_embeddings), total=len(all_queries)):
        # Extract the query ID and text for the current query
        query_id = query['query_id']
        query_text = query['title'] if isinstance(query, dict) else query

        # Get the set of relevant document IDs for the current query based on the relevance annotations in 'qrels'
        relevant_docs = {qrel.doc_id for qrel in qrels if qrel.query_id == query_id}
        ideal_scores = [qrel.relevance for qrel in qrels if qrel.query_id == query_id]

        # Sparse Retrieval using BM25
        sparse_indices, sparse_scores = bm25_retrieve(query_text, bm25)                 # Retrieve the top-k BM25 documents and their scores
        sparse_docs = [all_docs[idx]['doc_id'] for idx in sparse_indices]               # Get document IDs from the indices
        results["sparse"].append({"query": query, "results": sparse_docs})              # Store the BM25 results for the current query

        sparse_dcg = dcg_at_k(sparse_scores, k=5)
        sparse_ndcg = ndcg_at_k(sparse_scores, ideal_scores, k=5)
        sparse_recall = recall_at_k(sparse_docs, relevant_docs, k=5)
        metrics["sparse"].append({"dcg@5": sparse_dcg, "ndcg@5": sparse_ndcg, "recall@5": sparse_recall})

        # Dense Retrieval using cosine similarity
        dense_indices, dense_scores = dense_retrieve(query_embedding, doc_embeddings)   # Retrieve the top-k documents based on cosine similarity of embeddings
        dense_docs = [all_docs[idx]['doc_id'] for idx in dense_indices]
        results["dense"].append({"query": query, "results": dense_docs})

        dense_dcg = dcg_at_k(dense_scores, k=5)
        dense_ndcg = ndcg_at_k(dense_scores, ideal_scores, k=5)
        dense_recall = recall_at_k(dense_docs, relevant_docs, k=5)
        metrics["dense"].append({"dcg@5": dense_dcg, "ndcg@5": dense_ndcg, "recall@5": dense_recall})

        # Rank Fusion Retrieval by combining sparse (BM25) and dense result
        fusion_indices, fusion_scores = fusion_retrieve(                                # Combine BM25 and cosine similarity results
            query_embedding, doc_embeddings, query_text
        )
        fusion_docs = [all_docs[idx]['doc_id'] for idx in fusion_indices]
        results["rank_fusion"].append({"query": query, "results": fusion_docs})

        fusion_dcg = dcg_at_k(fusion_scores, k=5)
        fusion_ndcg = ndcg_at_k(fusion_scores, ideal_scores, k=5)
        fusion_recall = recall_at_k(fusion_docs, relevant_docs, k=5)
        metrics["rank_fusion"].append({"dcg@5": fusion_dcg, "ndcg@5": fusion_ndcg, "recall@5": fusion_recall})

        # Cascade Retrieval: First use BM25, then re-rank using dense retrieval
        cascade_indices, cascade_scores = cascade_retrieve(                             # Perform cascading retrieval
            query_embedding, doc_embeddings, query_text
        )
        cascade_docs = [all_docs[idx]['doc_id'] for idx in cascade_indices]
        results["cascade"].append({"query": query, "results": cascade_docs})

        cascade_dcg = dcg_at_k(cascade_scores, k=5)
        cascade_ndcg = ndcg_at_k(cascade_scores, ideal_scores, k=5)
        cascade_recall = recall_at_k(cascade_docs, relevant_docs, k=5)
        metrics["cascade"].append({"dcg@5": cascade_dcg, "ndcg@5": cascade_ndcg, "recall@5": cascade_recall})


    # Save results and metrics to JSON files
    print("Saving results and metrics.")
    with open("retrieval_results.json", "w") as f:
        json.dump(results, f, indent=4)
    with open("retrieval_metrics.json", "w") as f:
        json.dump(metrics, f, indent=4)
    print("Retrieval results and metrics saved to files.")

    return results, metrics


results, metrics = run_retrieval_experiments()
metrics_average = calculate_average_metrics(metrics)

print("result for each retriving method")
print(metrics_average)


Running retrieval experiments on all queries.


  0%|          | 0/50 [00:00<?, ?it/s]

[10.11986678 10.09531025 10.05892626  9.75917639  9.63448018]
[2, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 2, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 2, 0, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1, 2, 0, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 2, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0

  2%|▏         | 1/50 [00:03<02:57,  3.61s/it]

[19.2632898  19.22108577 19.22108577 18.36905419 18.08809198]
[2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0

  4%|▍         | 2/50 [00:06<02:32,  3.18s/it]

[0.46400164 0.42140816 0.407041   0.40595646 0.39801061]
[2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 

  6%|▌         | 3/50 [00:09<02:28,  3.15s/it]

[0.48416384 0.47133623 0.43547137 0.43227159 0.42422282]
[1, 0, 1, 2, 0, 2, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 0, 1, 0, 1, 0, 0, 2, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 2, 1, 

  8%|▊         | 4/50 [00:15<03:22,  4.41s/it]

[0.45952635 0.4555511  0.44248468 0.4212468  0.42007309]
[0, 0, 1, 1, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 2, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 2, 1, 0, 2, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 2, 1, 

 10%|█         | 5/50 [00:20<03:22,  4.49s/it]

[0.45276024 0.42713137 0.41239747 0.40923459 0.39950988]
[0, 2, 1, 2, 0, 2, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 2, 1, 0, 2, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 1, 0, 2, 2, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 1, 2, 2, 2, 0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 1, 2, 2, 1, 1, 2, 1, 0, 0, 0, 2, 0, 1, 2, 0, 1, 2, 0, 2, 1, 2, 2, 1, 0, 1, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 2, 2, 0, 2, 

 12%|█▏        | 6/50 [00:23<02:47,  3.81s/it]

[0.57776974 0.4497627  0.44872491 0.43198802 0.42272169]
[1, 0, 0, 2, 2, 1, 0, 2, 2, 0, 2, 1, 0, 2, 0, 1, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 1, 0, 1, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 2, 1, 0, 0, 2, 1, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 1, 1, 0, 2, 0, 1, 2, 0, 1, 1, 0, 0, 1, 2, 2, 0, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 0, 2, 2, 2, 1, 0, 0, 2, 1, 2, 1, 2, 0, 0, 1, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0, 1, 1, 0, 2, 2, 0, 2, 1, 2, 2, 1, 1, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 0, 2, 0, 1, 2, 0, 1, 0, 2, 1, 2, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 1, 2, 2, 2, 2, 1, 1, 2, 0, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 

 14%|█▍        | 7/50 [00:25<02:26,  3.41s/it]

[0.53091517 0.50593394 0.49804918 0.48037557 0.47555986]
[2, 0, 0, 0, 0, 0, 2, 0, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 1, 0, 0, 2, 0, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 1, 2, 

 16%|█▌        | 8/50 [00:27<02:08,  3.05s/it]

[0.49132228 0.46545542 0.44020071 0.43584098 0.43169723]
[1, 1, 1, 0, 1, 2, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 1, 2, 0, 2, 0, 0, 2, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 1, 2, 1, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 1, 0, 0, 2, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 1, 0, 1, 0, 0, 0, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 

 18%|█▊        | 9/50 [00:30<02:00,  2.93s/it]

[0.55461383 0.52628426 0.51789995 0.49955605 0.46756822]
[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 

 20%|██        | 10/50 [00:33<02:02,  3.07s/it]

[0.48098764 0.44326818 0.43959839 0.43587744 0.42481988]
[0, 2, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 1, 0, 0, 1, 2, 2, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1, 0, 2, 2, 2, 0, 0, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 2, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 1, 1, 1, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 2, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 2, 0, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 1, 1, 

 22%|██▏       | 11/50 [00:36<01:58,  3.03s/it]

[0.43430882 0.42102422 0.4006707  0.39208718 0.39085572]
[0, 1, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 1, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 1, 1, 1, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 2, 1, 0, 0, 

 24%|██▍       | 12/50 [00:39<01:44,  2.75s/it]

[0.4356447  0.42552641 0.41831573 0.36820297 0.36327068]
[0, 2, 1, 0, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 2, 0, 2, 0, 0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 1, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 2, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 

 26%|██▌       | 13/50 [00:41<01:39,  2.68s/it]

[0.38543827 0.38491469 0.36730935 0.34180657 0.33873411]
[1, 2, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 2, 2, 1, 2, 0, 2, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 0, 1, 0, 0, 2, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 

 28%|██▊       | 14/50 [00:43<01:32,  2.56s/it]

[0.44346599 0.3935299  0.37917896 0.3545331  0.35180608]
[0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 2, 0, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 

 30%|███       | 15/50 [00:46<01:26,  2.47s/it]

[0.43388711 0.38673993 0.38045745 0.36422297 0.36422297]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 

 32%|███▏      | 16/50 [00:50<01:41,  2.99s/it]

[0.45788711 0.42794892 0.3833749  0.38149602 0.34407205]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 

 34%|███▍      | 17/50 [00:53<01:40,  3.04s/it]

[0.41651216 0.40336234 0.35249451 0.35023135 0.34832225]
[1, 2, 1, 1, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 2, 0, 1, 0, 1, 1, 2, 0, 1, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 2, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 2, 2, 0, 2, 0, 0, 1, 0, 2, 2, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 0, 1, 1, 0, 2, 0, 0, 0, 1, 2, 0, 2, 1, 0, 0, 0, 1, 1, 0, 1, 2, 0, 1, 2, 0, 0, 2, 0, 1, 0, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 1, 0, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 2, 2, 1, 0, 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 2, 2, 0, 0, 2, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 0, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0, 0, 2, 

 36%|███▌      | 18/50 [00:55<01:29,  2.81s/it]

[0.45836285 0.44695222 0.42188723 0.40458488 0.39664086]
[1, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 2, 0, 2, 0, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 1, 1, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 1, 1, 2, 2, 1, 1, 1, 0, 0, 2, 0, 0, 2, 1, 2, 0, 0, 1, 0, 2, 1, 1, 2, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 2, 2, 1, 1, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 0, 2, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 2, 2, 0, 

 38%|███▊      | 19/50 [00:58<01:26,  2.78s/it]

[0.42170006 0.3970941  0.38870711 0.38762603 0.37605381]
[0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

 40%|████      | 20/50 [01:01<01:23,  2.80s/it]

[0.45281557 0.4188544  0.40817666 0.37158374 0.33116566]
[0, 2, 2, 2, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 2, 1, 1, 0, 2, 0, 2, 1, 0, 1, 0, 2, 2, 1, 0, 2, 1, 2, 2, 0, 2, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 2, 1, 1, 0, 2, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 2, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 0, 2, 1, 2, 2, 0, 1, 2, 0, 2, 1, 1, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 2, 0, 2, 1, 0, 0, 2, 1, 0, 2, 2, 1, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 1, 2, 1, 0, 1, 0, 1, 0, 0, 1, 2, 2, 2, 2, 1, 1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 1, 1, 2, 2, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 1, 2, 0, 2, 2, 1, 0, 0, 0, 2, 1, 2, 1, 1, 0, 2, 1, 2, 2, 2, 0, 2, 2, 1, 2, 0, 1, 2, 1, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1, 0, 2, 0, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 1, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0, 2, 2, 1, 0, 2, 1, 2, 0, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 1, 2, 1, 2, 2, 

 42%|████▏     | 21/50 [01:03<01:15,  2.60s/it]

[0.42496979 0.40146894 0.36009894 0.35823521 0.3565285 ]
[0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 2, 1, 0, 2, 0, 0, 2, 0, 1, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 0, 1, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 1, 2, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 1, 0, 2, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 1, 

 44%|████▍     | 22/50 [01:06<01:16,  2.73s/it]

[0.47269748 0.42974747 0.42362138 0.41766246 0.41039647]
[1, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 2, 2, 0, 2, 1, 0, 1, 2, 1, 1, 2, 2, 2, 1, 0, 1, 2, 2, 0, 0, 0, 2, 1, 1, 2, 0, 2, 1, 0, 0, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 1, 0, 0, 0, 1, 1, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 2, 1, 0, 0, 0, 2, 0, 2, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 1, 0, 0, 0, 2, 1, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 2, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 1, 

 46%|████▌     | 23/50 [01:09<01:14,  2.77s/it]

[0.52888346 0.43559864 0.41185658 0.40805416 0.38098175]
[0, 2, 2, 2, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 1, 0, 1, 2, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 2, 2, 2, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 

 48%|████▊     | 24/50 [01:12<01:11,  2.77s/it]

[0.45638936 0.45321864 0.42294055 0.39902805 0.39044266]
[2, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 1, 1, 0, 2, 2, 0, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 0, 0, 2, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 

 50%|█████     | 25/50 [01:15<01:11,  2.87s/it]

[0.47521682 0.39317639 0.37926059 0.32978504 0.32702396]
[2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 1, 0, 0, 1, 2, 0, 0, 2, 2, 2, 2, 0, 2, 1, 1, 0, 2, 1, 1, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 1, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 2, 0, 

 52%|█████▏    | 26/50 [01:17<01:04,  2.70s/it]

[0.52025261 0.49576737 0.4190194  0.41346085 0.39209261]
[1, 2, 2, 0, 0, 2, 0, 1, 0, 1, 1, 1, 0, 0, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 1, 0, 0, 1, 0, 2, 0, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 0, 0, 0, 2, 2, 0, 2, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 1, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0, 1, 2, 0, 2, 1, 0, 2, 1, 2, 0, 2, 2, 1, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 

 54%|█████▍    | 27/50 [01:19<00:57,  2.51s/it]

[0.41977317 0.40820542 0.39917268 0.39633256 0.39428704]
[1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 1, 0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 2, 2, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 2, 1, 0, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 1, 2, 0, 1, 2, 2, 0, 0, 2, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 2, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 2, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 2, 0, 0, 1, 1, 2, 0, 1, 2, 2, 2, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 1, 0, 1, 2, 2, 0, 0, 1, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 2, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0, 1, 0, 0, 

 56%|█████▌    | 28/50 [01:23<01:05,  2.96s/it]

[0.43415583 0.40590854 0.38924215 0.37125857 0.36438771]
[1, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 0, 2, 0, 0, 1, 2, 2, 1, 2, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 1, 2, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2, 2, 0, 2, 2, 1, 1, 0, 2, 0, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 1, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 0, 1, 0, 1, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 

 58%|█████▊    | 29/50 [01:29<01:19,  3.80s/it]

[0.59962853 0.33615078 0.32639728 0.32317512 0.31478537]
[0, 2, 0, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 1, 2, 1, 0, 0, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 2, 0, 1, 2, 1, 2, 0, 2, 1, 1, 0, 2, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0, 2, 1, 1, 2, 2, 2, 2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 2, 2, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 2, 0, 2, 0, 1, 1, 1, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 2, 0, 2, 0, 0, 1, 0, 2, 2, 0, 2, 1, 0, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 2, 2, 0, 1, 2, 2, 2, 0, 0, 2, 1, 2, 0, 1, 0, 0, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 0, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 

 60%|██████    | 30/50 [01:32<01:09,  3.48s/it]

[0.34020289 0.33062246 0.3170281  0.29841231 0.29021006]
[2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 2, 1, 0, 0, 0, 1, 2, 2, 2, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 2, 0, 0, 2, 1, 0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 0, 1, 2, 0, 0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 2, 

 62%|██████▏   | 31/50 [01:34<01:03,  3.32s/it]

[0.37428057 0.32481487 0.30799098 0.30468415 0.29281247]
[2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 

 64%|██████▍   | 32/50 [01:37<00:53,  2.95s/it]

[0.50290166 0.46524589 0.4252811  0.41299887 0.39854017]
[0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 

 66%|██████▌   | 33/50 [01:39<00:47,  2.77s/it]

[0.52365594 0.39411949 0.37136664 0.36717216 0.36681996]
[0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 1, 2, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 1, 2, 0, 0, 0, 0, 2, 

 68%|██████▊   | 34/50 [01:42<00:44,  2.76s/it]

[0.38669564 0.38270001 0.32039951 0.30157231 0.27278987]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 

 70%|███████   | 35/50 [01:46<00:49,  3.29s/it]

[0.39969899 0.36276504 0.36020273 0.36017631 0.33936482]
[0, 0, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 

 72%|███████▏  | 36/50 [01:49<00:44,  3.20s/it]

[0.42457435 0.42108554 0.3926466  0.37082002 0.36818723]
[2, 2, 2, 2, 0, 0, 2, 1, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 1, 2, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 

 74%|███████▍  | 37/50 [01:52<00:40,  3.13s/it]

[0.46319433 0.45873864 0.35845437 0.32979426 0.3241311 ]
[0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 2, 2, 0, 2, 1, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 0, 1, 0, 2, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 2, 2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 2, 2, 0, 2, 0, 1, 0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 1, 2, 2, 1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 2, 0, 1, 0, 2, 2, 1, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2, 

 76%|███████▌  | 38/50 [01:55<00:37,  3.11s/it]

[0.42299287 0.40364481 0.37632092 0.36968686 0.36191379]
[1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 0, 2, 2, 2, 0, 2, 1, 1, 1, 0, 2, 2, 2, 1, 1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 2, 0, 2, 1, 1, 0, 1, 0, 2, 0, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1, 0, 2, 0, 1, 1, 0, 0, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 0, 2, 2, 1, 2, 1, 1, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 0, 0, 2, 1, 2, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 0, 0, 2, 1, 0, 2, 1, 2, 1, 2, 0, 0, 1, 2, 2, 1, 2, 2, 0, 2, 1, 1, 1, 2, 2, 0, 2, 0, 1, 0, 0, 1, 1, 2, 0, 2, 1, 1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 2, 2, 2, 0, 1, 1, 0, 2, 1, 1, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 2, 2, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 0, 2, 1, 1, 

 78%|███████▊  | 39/50 [01:58<00:32,  2.97s/it]

[0.47043297 0.45591811 0.41547516 0.35501257 0.35332132]
[0, 1, 1, 0, 1, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 1, 1, 1, 2, 2, 0, 0, 2, 1, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 0, 2, 1, 2, 2, 1, 2, 0, 1, 2, 1, 2, 1, 2, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 1, 2, 2, 0, 2, 1, 2, 2, 2, 0, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 0, 1, 2, 1, 1, 2, 2, 0, 2, 2, 1, 2, 2, 1, 1, 2, 0, 1, 2, 2, 0, 2, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 0, 2, 2, 0, 1, 0, 2, 0, 1, 1, 2, 2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 

 80%|████████  | 40/50 [02:01<00:29,  2.94s/it]

[0.48352619 0.44328221 0.41485473 0.37259006 0.36878296]
[2, 2, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 1, 0, 2, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 1, 0, 0, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0, 2, 0, 1, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 1, 0, 2, 2, 2, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1, 0, 0, 1, 0, 0, 2, 2, 1, 2, 2, 2, 0, 0, 1, 0, 1, 2, 2, 1, 0, 0, 0, 1, 2, 2, 

 82%|████████▏ | 41/50 [02:04<00:26,  2.97s/it]

[0.48800967 0.44098074 0.37927183 0.37320907 0.36605066]
[0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 1, 2, 0, 0, 0, 2, 2, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 1, 1, 0, 

 84%|████████▍ | 42/50 [02:06<00:22,  2.85s/it]

[0.48833511 0.44561548 0.4037463  0.39355842 0.37080367]
[0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 1, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 

 86%|████████▌ | 43/50 [02:09<00:18,  2.67s/it]

[0.48812098 0.48052859 0.47881519 0.47693076 0.42720611]
[0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 1, 0, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 2, 2, 0, 2, 2, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 2, 2, 1, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 1, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 2, 

 88%|████████▊ | 44/50 [02:12<00:16,  2.78s/it]

[0.55993798 0.51364506 0.46396553 0.45815179 0.38511903]
[2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 0, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 1, 1, 1, 1, 2, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 2, 2, 1, 1, 2, 0, 0, 2, 0, 0, 1, 2, 0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 1, 0, 0, 2, 1, 2, 1, 0, 0, 1, 2, 2, 0, 0, 0, 1, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 2, 1, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 

 90%|█████████ | 45/50 [02:14<00:13,  2.77s/it]

[0.43826601 0.43593808 0.41731816 0.41149533 0.37609838]
[2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 1, 2, 2, 1, 0, 2, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 1, 2, 1, 2, 2, 0, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 1, 2, 2, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 2, 0, 2, 0, 0, 1, 1, 2, 2, 2, 0, 2, 0, 1, 0, 2, 1, 2, 2, 0, 2, 2, 0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 2, 1, 0, 2, 1, 0, 1, 1, 2, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 0, 2, 

 92%|█████████▏| 46/50 [02:17<00:10,  2.75s/it]

[0.37719147 0.36288139 0.36182614 0.34619765 0.33652039]
[0, 1, 0, 0, 2, 1, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 0, 2, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 2, 0, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 2, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 

 94%|█████████▍| 47/50 [02:21<00:08,  2.98s/it]

[0.4980577  0.34258891 0.33444127 0.3194707  0.31508704]
[0, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 1, 2, 0, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 2, 1, 2, 0, 0, 2, 2, 0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 1, 2, 1, 0, 0, 0, 0, 1, 2, 2, 1, 1, 0, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 1, 0, 1, 0, 2, 1, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 1, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 1, 2, 0, 2, 0, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 2, 2, 0, 2, 0, 2, 0, 1, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2, 2, 1, 2, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 

 96%|█████████▌| 48/50 [02:23<00:05,  2.81s/it]

[0.49131536 0.42137511 0.4185598  0.40907083 0.396126  ]
[0, 2, 0, 0, 1, 0, 1, 1, 0, 0, 2, 0, 0, 2, 1, 0, 1, 0, 2, 2, 2, 0, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 2, 0, 1, 0, 0, 2, 1, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 1, 0, 0, 0, 1, 0, 2, 0, 1, 2, 0, 2, 1, 0, 1, 0, 1, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 2, 1, 0, 0, 2, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 2, 2, 0, 0, 0, 2, 1, 1, 2, 0, 0, 2, 0, 1, 1, 0, 2, 0, 0, 2, 0, 0, 2, 1, 0, 1, 1, 2, 0, 1, 2, 0, 0, 0, 1, 1, 2, 1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 2, 2, 1, 2, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 

 98%|█████████▊| 49/50 [02:25<00:02,  2.65s/it]

[0.4248996  0.36556486 0.34907782 0.34904706 0.34487161]
[0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

100%|██████████| 50/50 [02:28<00:00,  2.98s/it]

[0.37496776 0.34847578 0.34692542 0.33831401 0.31932035]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

# Section 4: QA with Language Model

In [38]:
# QA for the first query
QUERY_INDEX = 3                                                     # Index of the query to be used for retrieval
query = all_queries[QUERY_INDEX - 1]                                # Select the query from the list based on the index
query_text = query['title'] if isinstance(query, dict) else query   # Get the query text

# Retrieval calls:

# Perform dense retrieval using query embedding and document embeddings
dense_top_k_indices, dense_top_k_scores = dense_retrieve(query_embeddings[QUERY_INDEX], doc_embeddings)
# Perform sparse retrieval using BM25 on the query text
sparse_top_k_indices, sparse_top_k_scores = bm25_retrieve(query_text, bm25)
# Perform rank fusion retrieval by combining BM25 and dense retrieval results
rank_top_k_indices, rank_top_k_scores = fusion_retrieve(
    query_embeddings[QUERY_INDEX],
    doc_embeddings,
    query_text
)
# Perform cascading retrieval: first BM25, then re-rank with dense retrieval
cascading_top_k_indices, cascading_top_k_scores = cascade_retrieve(
    query_embeddings[QUERY_INDEX],
    doc_embeddings,
    query_text
)

# Get retrieved documents for each method
dense_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(dense_top_k_indices)]
sparse_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(sparse_top_k_indices)]
rank_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(rank_top_k_indices)]
cascading_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(cascading_top_k_indices)]

# Definition of the model that will be used to generate the various responses.
lm_pipeline = pipeline("text-generation",
                      model="meta-llama/Llama-3.2-1B",
                      device=0 if device == "cuda" else -1)

config.json:   0%|          | 0.00/843 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

Device set to use cuda:0


#### Question-answering using DENSE RETRIEVAL

In [39]:
print("------------------ DENSE RETRIEVAL ----------------------\n")
context = "\n".join(dense_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]
response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()

print(f"------------------ Response ------------------\n{response}")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


------------------ DENSE RETRIEVAL ----------------------

----------------- Length of the prompt -----------------
795 words
------------------------ Prompt ------------------------
Context:
Document 1: Population density, behaviour and cultural habits strongly influence the spread of pathogens. Consequently, key epidemiological parameters may vary from country to country. Confirmed COVID-19 cases in in China have been used to estimate those parameters, that vary largely (reviewed in 1). The estimates also depend on testing frequency and case definitions that are prone to change during ongoing epidemics, providing additional uncertainties. The rise in fatal cases due to SARS-CoV2 could be a more reliable parameter, since missing of deaths is less likely. In the absence of changes in the management of severe COVID-19 cases, the rise in death cases should be proportional to the rise in virus infections. Although the fluctuating low numbers of fatal cases very early in the epidemic may l

#### Question-answering using SPARSE RETRIEVAL

In [40]:
print("------------------ SPARSE RETRIEVAL ----------------------\n")
context = "\n".join(sparse_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


------------------ SPARSE RETRIEVAL ----------------------

----------------- Length of the prompt -----------------
465 words
------------------------ Prompt ------------------------
Context:
Document 1: Those downplaying the coronavirus ignore our lack of immunity and vaccines
Document 2: Other reasons rather then absence of prior immunity could play a crucial role in the children coronavirus dilemma
Document 3: Despite various levels of preventive measures, in 2020 many countries have suffered severely from the coronavirus 2019 (COVID-19) pandemic caused by the severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) virus. We show that population heterogeneity can significantly impact disease-induced immunity as the proportion infected in groups with the highest contact rates is greater than in groups with low contact rates. We estimate that if R(0) = 2.5 in an age-structured community with mixing rates fitted to social activity then the disease-induced herd immunity level can 

#### Question-answering using RANK FUSION

In [41]:
print("------------------ RANK FUSION ----------------------\n")
context = "\n".join(rank_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


------------------ RANK FUSION ----------------------

----------------- Length of the prompt -----------------
741 words
------------------------ Prompt ------------------------
Context:
Document 1: Despite various levels of preventive measures, in 2020 many countries have suffered severely from the coronavirus 2019 (COVID-19) pandemic caused by the severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) virus. We show that population heterogeneity can significantly impact disease-induced immunity as the proportion infected in groups with the highest contact rates is greater than in groups with low contact rates. We estimate that if R(0) = 2.5 in an age-structured community with mixing rates fitted to social activity then the disease-induced herd immunity level can be around 43%, which is substantially less than the classical herd immunity level of 60% obtained through homogeneous immunization of the population. Our estimates should be interpreted as an illustration of how popula

#### Question-answering using CASCADING RETRIEVAL

In [42]:
print("------------------ CASCADING RETRIEVAL ----------------------\n")
context = "\n".join(cascading_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


------------------ CASCADING RETRIEVAL ----------------------

----------------- Length of the prompt -----------------
465 words
------------------------ Prompt ------------------------
Context:
Document 1: Those downplaying the coronavirus ignore our lack of immunity and vaccines
Document 2: Other reasons rather then absence of prior immunity could play a crucial role in the children coronavirus dilemma
Document 3: Despite various levels of preventive measures, in 2020 many countries have suffered severely from the coronavirus 2019 (COVID-19) pandemic caused by the severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) virus. We show that population heterogeneity can significantly impact disease-induced immunity as the proportion infected in groups with the highest contact rates is greater than in groups with low contact rates. We estimate that if R(0) = 2.5 in an age-structured community with mixing rates fitted to social activity then the disease-induced herd immunity level c

#### Question-answering WITH NO CONTEXT PROVIDED WITH RAG

In [43]:

print("------------------ RESPONSE WITHOUT RAG ----------------------\n")
prompt = f"""Question:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"""

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


------------------ RESPONSE WITHOUT RAG ----------------------

----------------- Length of the prompt -----------------
20 words
------------------------ Prompt ------------------------
Question:
coronavirus immunity

Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):
------------------ Response ------------------
How long does immunity last after recovery from coronavirus?


In [44]:
import random

picked_queries = random.sample(all_queries, 5)

for q in picked_queries:

    # For each query, retrieve and rank documents independently
    query_text = q['title']
    cascading_top_k_indices, cascading_top_k_scores = cascade_retrieve(query_embeddings[QUERY_INDEX], doc_embeddings, query_text)

    # Use the top-k documents for that specific query
    cascading_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(cascading_top_k_indices)]
    cascading_context = "\n".join(cascading_retrieved_docs)

    # Repeat the process for rank fusion
    rank_top_k_indices, rank_top_k_scores = fusion_retrieve(query_embeddings[QUERY_INDEX], doc_embeddings, query_text)
    rank_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(rank_top_k_indices)]
    rank_fusion_context = "\n".join(rank_retrieved_docs)


    cascading_prompt = f"Context:\n{cascading_context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"
    rank_fusion_prompt = f"Context:\n{rank_fusion_context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

    # Generate response using language model
    cascading_response = lm_pipeline(cascading_prompt,
                           max_new_tokens=150,
                           temperature=0.7,
                           truncation=False)[0]["generated_text"]

    rank_fusion_response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.1,
                      truncation=False)[0]["generated_text"]

    # Extract the answer from the response
    cascading_response = cascading_response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
    rank_fusion_response = rank_fusion_response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()

    # Print the results
    print(f"\nQuery: {query_text}")
    print(f"Cascading Response: {cascading_response}")
    print(f"Rank Fusion Response: {rank_fusion_response}")
    print("------------------------------\n")


Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.



Query: COVID-19 outcomes in children
Cascading Response: The clinical presentation and outcomes of children with COVID-19 in Europe are still lacking. In this descriptive study, we report on 130 children with confirmed COVID-19 diagnosed by 28 centers (mostly hospitals), in 10 regions in Italy, during the first months of the pandemic. Among these, 67 (51.5%) had a relative with COVID-19 while 34 (26.2%) had comorbidities, with the most frequent being respiratory, cardiac, or neuromuscular chronic diseases. Overall, 98 (75.4%) had an asymptomatic or mild disease, 11 (8.5%) had moderate disease, 11 (8.5%) had a severe disease, and 9 (6
Rank Fusion Response: 1. The virus is transmitted by droplets. 2. The virus is transmitted by droplets. 3. The virus is transmitted by droplets. 4. The virus is transmitted by droplets. 5. The virus is transmitted by droplets. 6. The virus is transmitted by droplets. 7. The virus is transmitted by droplets. 8. The virus is transmitted by droplets. 9. The 

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.



Query: SARS-CoV-2 spike structure
Cascading Response: SARS-CoV-2 spike protein has been crystallized, and its structure has been determined. The structure of the spike protein was determined by crystallography. The structure of the spike protein is a trimeric protein that consists of three subunits. The three subunits of the spike protein are arranged in a triangular fashion with a central subunit forming a trimeric core. The spike protein has a surface area of 3000 A2 and a molecular weight of 300 kDa. The spike protein has a trimeric structure that consists of three subunits. Each subunit has a surface area of 1000 A2 and a molecular weight of 100 kDa. The spike protein has a trimeric structure
Rank Fusion Response: 1. The virus is spread by droplets. 2. The virus is spread by droplets. 3. The virus is spread by droplets. 4. The virus is spread by droplets. 5. The virus is spread by droplets. 6. The virus is spread by droplets. 7. The virus is spread by droplets. 8. The virus is spr

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.



Query: coronavirus hydroxychloroquine
Cascading Response: There have been controversies on the prophylactic effect of hydroxychloroquine against severe acute respiratory syndrome coronavirus-2 (SARS-CoV-2). We describe a patient, 60-year old Korean woman, with coronavirus disease 2019 (COVID-19) who had been taking hydroxychloroquine for 6 months. Her serum and saliva concentrations of hydroxychloroquine were 280 µg/L and 4,890 µg/L, respectively. The present case raises concerns on hydroxychloroquine's role as a prophylactic agent for COVID-19.

In the paper, the authors report the case of a 60-year-old Korean woman who was taking hydroxychloroquine for 6 months
Rank Fusion Response: 1. What is the immunity of a person who has been infected with coronavirus? 2. What is the immunity of a person who has been vaccinated with a vaccine against coronavirus? 3. What is the immunity of a person who has been infected with coronavirus and has been vaccinated with a vaccine against coronavirus

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.



Query: coronavirus remdesivir
Cascading Response: remdesivir is an investigational drug for the treatment of human coronavirus infection. Remdesivir is a phosphoramidate prodrug and is known to target viral RNA-dependent RNA polymerases. In this issue, Gordon et al. identify that remdesivir acts as a delayed RNA chain terminator for MERS-CoV polymerase complexes.

Question:
remdesivir
Rank Fusion Response: 1. What is the immunity of a person who has recovered from coronavirus? 2. What is the immunity of a person who has been vaccinated against coronavirus? 3. What is the immunity of a person who has been infected with coronavirus but has recovered? 4. What is the immunity of a person who has been infected with coronavirus but has not recovered? 5. What is the immunity of a person who has been infected with coronavirus but has not recovered and has not been vaccinated? 6. What is the immunity of a person who has been infected with coronavirus but has not recovered and has been vaccinat

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.



Query: coronavirus early symptoms
Cascading Response: coronavirus early symptoms

Explanation:
Rank Fusion Response: 1. The virus is transmitted through droplets. 2. The virus is transmitted through droplets. 3. The virus is transmitted through droplets. 4. The virus is transmitted through droplets. 5. The virus is transmitted through droplets. 6. The virus is transmitted through droplets. 7. The virus is transmitted through droplets. 8. The virus is transmitted through droplets. 9. The virus is transmitted through droplets. 10. The virus is transmitted through droplets. 11. The virus is transmitted through droplets. 12. The virus is transmitted through droplets. 13. The virus is transmitted through droplets. 14. The virus is transmitted
------------------------------

