In [12]:
!pip install ir_datasets
!pip install rank_bm25
!pip install sentence_transformers
!pip install pytrec_eval

python(96135) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


python(96159) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


python(96173) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


python(96192) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [13]:
from tqdm import tqdm
import json
import ir_datasets
import os
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
from rank_bm25 import BM25Okapi
from transformers import pipeline
import torch
from huggingface_hub import login
import pytrec_eval
import collections

api_key = "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"
login(token=api_key)

# Check GPU availability
def get_device():
    if torch.cuda.is_available():
        device = "cuda"
        gpu_properties = torch.cuda.get_device_properties(torch.cuda.current_device())
        print(f"Using GPU: {gpu_properties.name}")
        print(f"CUDA Cores: {gpu_properties.multi_processor_count}")
        print(f"Total Memory: {gpu_properties.total_memory / 1e9:.2f} GB")
        print(f"Compute Capability: {gpu_properties.major}.{gpu_properties.minor}")
    elif torch.backends.mps.is_available():
        device = "mps"
        print("Using MPS (Metal Performance Shaders)")
    else:
        device = "cpu"
        print("Using CPU")
    return device

device = get_device()


The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /Users/danielnamaki/.cache/huggingface/token
Login successful
Using MPS (Metal Performance Shaders)


# Section 1: Dataset loading and preparation

In [14]:
# Load dataset
print("Loading the trec covid dataset...")
dataset = ir_datasets.load("beir/nfcorpus/test")

# Prepare documents and queries
print("Preparing documents and queries...")
# for doc in dataset.docs_iter():
#   print(doc)
#   break
all_docs = [{"doc_id": doc.doc_id, "abstract": doc.title + doc.text} for doc in dataset.docs_iter()]
all_queries = [{"query_id": query.query_id, "title": query.text} for query in dataset.queries_iter()]

# Print dataset size information
print(f"Summary: {len(all_docs)} documents and {len(all_queries)} queries are available in the dataset.")

tokenized_docs = [doc['abstract'].split() for doc in all_docs]

Loading the trec covid dataset...
Preparing documents and queries...
Summary: 3633 documents and 323 queries are available in the dataset.


In [15]:
# convert qrels to a dictionary
qrels_dict = collections.defaultdict(dict)
for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id][qrel.doc_id] = int(qrel.relevance)

# Section 2: Embeddings generation

In [16]:
# Load or generate embeddings
def generate_embeddings():
    if os.path.exists("trec_covid_doc_embeddings.csv") and os.path.exists("trec_covid_query_embeddings.csv"):
        print("Loading precomputed embeddings...")
        doc_embeddings = pd.read_csv("trec_covid_doc_embeddings.csv").values
        query_embeddings = pd.read_csv("trec_covid_query_embeddings.csv").values
    else:
        print("No precomputed embeddings found.")
        print("Generating new embeddings using SentenceTransformer model 'sentence-transformers/all-MiniLM-L6-v2'.")
        model = SentenceTransformer("intfloat/e5-small-v2", device=device)
        doc_embeddings = model.encode([doc["abstract"] for doc in all_docs], batch_size=32, show_progress_bar=True, normalize_embeddings=True)
        query_embeddings = model.encode([query['title'] for query in all_queries], batch_size=32, show_progress_bar=True, normalize_embeddings=True)

        # Save embeddings for future use
        pd.DataFrame(doc_embeddings).to_csv("trec_covid_doc_embeddings.csv", index=False)
        pd.DataFrame(query_embeddings).to_csv("trec_covid_query_embeddings.csv", index=False)

    return doc_embeddings, query_embeddings

doc_embeddings, query_embeddings = generate_embeddings()

Loading precomputed embeddings...


# Section 3: Retrieval implementation

### Evaluation metrics
The following functions are used to evaluate the quality of document retrieval methods based on the ranked list of documents returned for a given query.

In [17]:
# Function to prepare run data for pytrec_eval
def prepare_run_data(results):
    """
    Prepares the run data in the format expected by pytrec_eval.
    Converts numpy scores to native Python float for compatibility.
    """
    run = {}
    for query_results in results:
        query_id = query_results['query']['query_id']
        run[query_id] = {}
        for doc_id, score in zip(query_results['results'], query_results['scores']):
            run[query_id][doc_id] = float(score)  # Convert numpy type to float
    return run

### Document Retrieval Methods

1. **BM25 Sparse Retrieval**:
   - The **BM25 algorithm** is used to perform sparse retrieval on tokenized documents by calculating a relevance score for each document based on the query. It then returns the indices and relevance scores of the top-k most relevant documents.

2. **Dense Retrieval**:
   - **Dense retrieval** is performed by calculating the cosine similarity between the query embedding and the document embeddings. The top-k documents with the highest similarity scores are returned.

3. **Rank Fusion Retrieval**:
   - Results from both **BM25** and **dense retrieval** are combined using a **rank fusion** technique. Scores from both methods are normalized, weighted by a parameter `alpha`, and the top-k documents are returned based on the combined scores.

4. **Cascading Retrieval**:
   - Initially, a set of documents is retrieved using **BM25**. These documents are then re-ranked using dense retrieval, with a similarity threshold applied to filter documents. The top-k documents are returned based on the final ranking.

In [18]:
# BM25 Sparse Retrieval
def bm25_retrieve(query, bm25, top_k=5):
    """
    Perform sparse retrieval using BM25 on the tokenized documents.
    Returns the indices and scores of the top-k documents.
    """
    tokenized_query = query.split()                                             # Tokenize the query into words
    scores = bm25.get_scores(tokenized_query)                                   # Get BM25 scores for all documents
    top_k_indices = np.argsort(scores)[-top_k:][::-1]                           # Get indices of top-k documents based on BM25 score
    return top_k_indices, scores[top_k_indices]

# Dense Retrieval
def dense_retrieve(query_embedding, doc_embeddings, top_k=5):
    """
    Perform dense retrieval using cosine similarity between query and document embeddings.
    Returns the indices and similarities of the top-k documents.
    """
    similarities = cosine_similarity([query_embedding], doc_embeddings)[0]      # Compute cosine similarity
    top_k_indices = np.argsort(similarities)[-top_k:][::-1]                     # Get top-k indices based on similarity
    return top_k_indices, similarities[top_k_indices]

# Rank Fusion Retrieval
def fusion_retrieve(dense_query_embedding, doc_embeddings, query, top_k=5, alpha=0.5):
    """
    Implementa il rank fusion riutilizzando le funzioni esistenti di retrieval.
    """

    # Perform BM25 retrieval and dense retrieval
    sparse_indices, sparse_scores = bm25_retrieve(query, bm25)
    dense_indices, dense_scores = dense_retrieve(dense_query_embedding, doc_embeddings)

    # Initialize score arrays
    all_sparse_scores = np.zeros(len(doc_embeddings))
    all_dense_scores = np.zeros(len(doc_embeddings))

    # Fill score arrays with BM25 and dense scores
    all_sparse_scores[sparse_indices] = sparse_scores
    all_dense_scores[dense_indices] = dense_scores

    if np.min(all_sparse_scores) == np.max(all_sparse_scores):
        print("All sparse scores are the same.")
        print(sparse_scores)

    if np.min(all_dense_scores) == np.max(all_dense_scores):
        print("All dense scores are the same.")
        print(dense_scores)

    # Normalize scores
    all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
    all_dense_scores = (all_dense_scores - all_dense_scores.min()) / (all_dense_scores.max() - all_dense_scores.min())

    print("BM25 Scores:", all_sparse_scores)
    print("Dense Scores:", all_dense_scores)

    # Combine scores using the alpha parameter
    combined_scores = alpha * all_dense_scores + (1 - alpha) * all_sparse_scores

    # Retrieve the top-k results based on combined scores
    top_k_indices = np.argsort(combined_scores)[-top_k:][::-1]
    return top_k_indices, combined_scores[top_k_indices]

# Cascading Retrieval
def cascade_retrieve(dense_query_embedding, doc_embeddings, query, initial_k=100, final_k=5, dense_threshold=0.7):
    """
    Perform cascading retrieval: sparse retrieval followed by dense re-ranking.
    Filters documents based on a similarity threshold and returns the top-k results.
    """
    # Stage 1: BM25 to get initial candidates
    initial_indices, _ = bm25_retrieve(query, bm25, top_k=initial_k)

    # Stage 2: Dense re-ranking of candidate documents
    candidate_embeddings = doc_embeddings[initial_indices]
    _, dense_scores = dense_retrieve(dense_query_embedding, candidate_embeddings, top_k=len(initial_indices))

    # Filter candidates by similarity threshold
    qualified_mask = dense_scores >= dense_threshold
    if np.sum(qualified_mask) >= final_k:
        # Select top-k qualified candidates
        qualified_indices = np.where(qualified_mask)[0]
        top_indices = qualified_indices[np.argsort(dense_scores[qualified_indices])[-final_k:][::-1]]
    else:
        # If there are not enough qualified candidates, select top-k by overall scores
        top_indices = np.argsort(dense_scores)[-final_k:][::-1]

    # Map filtered indices to original document IDs
    final_indices = initial_indices[top_indices]
    final_scores = dense_scores[top_indices]

    return final_indices, final_scores



In [19]:
# Initialize BM25 model
print("Initializing BM25 model.")
bm25 = BM25Okapi(tokenized_docs)

Initializing BM25 model.


This section of code performs several retrieval experiments using the four different Document Retrieval Methods described earlier.

In [20]:
# Run retrieval experiments
def run_retrieval_experiments():
    """
    Execute sparse, dense, rank fusion, and cascading retrieval for all queries.
    Save the results to a JSON file for further analysis.
    """
    results = {"sparse": [], "dense": [], "rank_fusion": [], "cascade": []}

    print("Running retrieval experiments on all queries.")

    # Iterate over each query and its embedding
    for query, query_embedding in tqdm(zip(all_queries, query_embeddings), total=len(all_queries)):
        # Extract the query ID and text for the current query
        query_id = query['query_id']
        query_text = query['title'] if isinstance(query, dict) else query

        # Sparse Retrieval using BM25
        sparse_indices, sparse_scores = bm25_retrieve(query_text, bm25)                 # Retrieve the top-k BM25 documents and their scores
        sparse_docs = [all_docs[idx]['doc_id'] for idx in sparse_indices]               # Get document IDs from the indices
        results["sparse"].append({"query": query, "results": sparse_docs, "scores": sparse_scores}) # Store the BM25 results for the current query

        # Dense Retrieval using cosine similarity
        dense_indices, dense_scores = dense_retrieve(query_embedding, doc_embeddings)   # Retrieve the top-k documents based on cosine similarity of embeddings
        dense_docs = [all_docs[idx]['doc_id'] for idx in dense_indices]
        results["dense"].append({"query": query, "results": dense_docs, "scores": dense_scores})

        # Rank Fusion Retrieval by combining sparse (BM25) and dense result
        fusion_indices, fusion_scores = fusion_retrieve(                                # Combine BM25 and cosine similarity results
            query_embedding, doc_embeddings, query_text
        )
        fusion_docs = [all_docs[idx]['doc_id'] for idx in fusion_indices]
        results["rank_fusion"].append({"query": query, "results": fusion_docs, "scores": fusion_scores})

        # Cascade Retrieval: First use BM25, then re-rank using dense retrieval
        cascade_indices, cascade_scores = cascade_retrieve(                             # Perform cascading retrieval
            query_embedding, doc_embeddings, query_text
        )
        cascade_docs = [all_docs[idx]['doc_id'] for idx in cascade_indices]
        results["cascade"].append({"query": query, "results": cascade_docs, "scores": cascade_scores})

    return results

results = run_retrieval_experiments()


Running retrieval experiments on all queries.


  0%|          | 1/323 [00:00<05:03,  1.06it/s]

BM25 Scores: [0.92101804 0.         0.         ... 0.         0.         0.        ]
Dense Scores: [0.99618964 0.99777083 0.         ... 0.         0.         0.        ]


  1%|          | 2/323 [00:01<04:17,  1.25it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0.         0.         0.99810841 ... 0.         0.         0.        ]


  1%|          | 3/323 [00:02<04:03,  1.32it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  2%|▏         | 6/323 [00:03<02:24,  2.19it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  2%|▏         | 7/323 [00:03<02:16,  2.31it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  2%|▏         | 8/323 [00:04<02:09,  2.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  3%|▎         | 9/323 [00:04<02:20,  2.24it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  3%|▎         | 11/323 [00:05<01:54,  2.72it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  4%|▎         | 12/323 [00:05<01:43,  3.02it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  4%|▍         | 13/323 [00:05<01:34,  3.27it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  5%|▍         | 15/323 [00:06<01:13,  4.17it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  5%|▌         | 17/323 [00:06<01:19,  3.86it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  6%|▌         | 18/323 [00:07<01:22,  3.69it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  6%|▌         | 20/323 [00:07<01:09,  4.34it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  7%|▋         | 22/323 [00:08<01:31,  3.29it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  7%|▋         | 23/323 [00:08<01:28,  3.40it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  8%|▊         | 25/323 [00:10<02:44,  1.81it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  8%|▊         | 26/323 [00:10<02:42,  1.83it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  8%|▊         | 27/323 [00:10<02:13,  2.21it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


  9%|▉         | 29/323 [00:12<02:40,  1.83it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0.         0.         0.         ... 0.         0.         0.99840037]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 10%|▉         | 31/323 [00:13<02:51,  1.70it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 10%|▉         | 32/323 [00:14<03:03,  1.58it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 10%|█         | 33/323 [00:14<03:04,  1.58it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 11%|█         | 35/323 [00:15<02:36,  1.84it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 11%|█         | 36/323 [00:16<02:27,  1.95it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 11%|█▏        | 37/323 [00:16<02:14,  2.12it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 12%|█▏        | 39/323 [00:18<02:42,  1.75it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 12%|█▏        | 40/323 [00:18<02:17,  2.06it/s]

BM25 Scores: [0. 0. 0. ... 1. 0. 0.]
Dense Scores: [0. 0. 0. ... 1. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 13%|█▎        | 43/323 [00:18<01:21,  3.42it/s]

BM25 Scores: [0.         0.         0.         ... 0.         0.         0.72765558]
Dense Scores: [0. 0. 0. ... 0. 0. 1.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 14%|█▎        | 44/323 [00:19<01:18,  3.56it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 14%|█▍        | 45/323 [00:19<01:15,  3.70it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 14%|█▍        | 46/323 [00:19<01:20,  3.44it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 15%|█▍        | 47/323 [00:20<01:23,  3.32it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 15%|█▍        | 48/323 [00:20<01:36,  2.85it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 15%|█▌        | 49/323 [00:20<01:38,  2.79it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 15%|█▌        | 50/323 [00:21<01:22,  3.32it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 16%|█▌        | 51/323 [00:21<01:17,  3.51it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 16%|█▌        | 52/323 [00:21<01:28,  3.07it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 16%|█▋        | 53/323 [00:21<01:12,  3.71it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 17%|█▋        | 56/323 [00:22<00:45,  5.83it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 18%|█▊        | 58/323 [00:22<00:39,  6.73it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 18%|█▊        | 59/323 [00:22<00:38,  6.86it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 19%|█▉        | 61/323 [00:23<00:52,  5.00it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 19%|█▉        | 62/323 [00:23<01:02,  4.16it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 20%|█▉        | 64/323 [00:23<01:00,  4.27it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 20%|██        | 66/323 [00:24<00:58,  4.42it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 21%|██        | 68/323 [00:24<00:53,  4.75it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 21%|██▏       | 69/323 [00:24<00:50,  5.04it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 22%|██▏       | 70/323 [00:25<01:04,  3.94it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 22%|██▏       | 71/323 [00:25<01:03,  3.99it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 23%|██▎       | 73/323 [00:25<00:51,  4.87it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 23%|██▎       | 74/323 [00:26<00:54,  4.58it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 23%|██▎       | 75/323 [00:26<00:58,  4.22it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 24%|██▎       | 76/323 [00:26<01:05,  3.76it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 24%|██▍       | 79/323 [00:27<00:52,  4.68it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: 

/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 25%|██▌       | 81/323 [00:27<00:49,  4.90it/s]

[0. 0. 0. ... 0. 0. 0.]


 25%|██▌       | 82/323 [00:28<01:35,  2.52it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 26%|██▌       | 83/323 [00:28<01:26,  2.76it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 26%|██▋       | 85/323 [00:29<01:08,  3.47it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 27%|██▋       | 86/323 [00:29<01:08,  3.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 28%|██▊       | 89/323 [00:30<00:54,  4.26it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 28%|██▊       | 90/323 [00:30<00:52,  4.41it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 29%|██▉       | 93/323 [00:30<00:35,  6.39it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 29%|██▉       | 94/323 [00:31<00:42,  5.41it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 30%|██▉       | 96/323 [00:31<00:50,  4.46it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 30%|███       | 98/323 [00:32<00:53,  4.24it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 31%|███       | 100/323 [00:32<01:02,  3.55it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 32%|███▏      | 102/323 [00:33<00:57,  3.87it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 32%|███▏      | 103/323 [00:33<01:02,  3.52it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 32%|███▏      | 104/323 [00:34<01:09,  3.15it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 33%|███▎      | 107/323 [00:34<00:52,  4.15it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 33%|███▎      | 108/323 [00:34<00:49,  4.37it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 34%|███▎      | 109/323 [00:35<00:52,  4.07it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 34%|███▍      | 110/323 [00:35<00:51,  4.11it/s]

BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 34%|███▍      | 111/323 [00:35<00:51,  4.11it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 35%|███▍      | 112/323 [00:36<01:05,  3.22it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 35%|███▍      | 113/323 [00:36<01:02,  3.34it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 36%|███▌      | 116/323 [00:36<00:42,  4.92it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 36%|███▌      | 117/323 [00:37<00:38,  5.30it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 37%|███▋      | 119/323 [00:37<00:32,  6.20it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 37%|███▋      | 121/323 [00:37<00:25,  7.93it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 38%|███▊      | 123/323 [00:37<00:22,  9.03it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 38%|███▊      | 124/323 [00:37<00:26,  7.57it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 39%|███▉      | 127/323 [00:38<00:28,  6.97it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 40%|███▉      | 128/323 [00:38<00:32,  5.98it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 40%|███▉      | 129/323 [00:38<00:36,  5.38it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 40%|████      | 130/323 [00:39<00:48,  3.95it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 41%|████      | 131/323 [00:39<00:43,  4.46it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 41%|████      | 132/323 [00:39<00:47,  3.99it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 41%|████      | 133/323 [00:39<00:45,  4.20it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 41%|████▏     | 134/323 [00:40<00:40,  4.62it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 42%|████▏     | 135/323 [00:40<00:39,  4.74it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 42%|████▏     | 136/323 [00:40<00:33,  5.57it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 42%|████▏     | 137/323 [00:40<00:34,  5.33it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 43%|████▎     | 140/323 [00:41<00:31,  5.73it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 44%|████▎     | 141/323 [00:41<00:39,  4.63it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 44%|████▍     | 142/323 [00:41<00:40,  4.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 44%|████▍     | 143/323 [00:42<00:47,  3.78it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 45%|████▍     | 145/323 [00:42<00:51,  3.48it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 45%|████▌     | 146/323 [00:42<00:46,  3.79it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 46%|████▌     | 148/323 [00:43<00:38,  4.55it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 46%|████▌     | 149/323 [00:43<00:40,  4.34it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 47%|████▋     | 151/323 [00:43<00:40,  4.27it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 47%|████▋     | 153/323 [00:44<00:38,  4.41it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 48%|████▊     | 155/323 [00:44<00:36,  4.54it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 49%|████▊     | 157/323 [00:45<00:31,  5.34it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 49%|████▉     | 158/323 [00:45<00:31,  5.24it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 49%|████▉     | 159/323 [00:45<00:26,  6.08it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 50%|████▉     | 160/323 [00:45<00:30,  5.38it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 50%|█████     | 162/323 [00:46<00:43,  3.69it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 51%|█████     | 164/323 [00:46<00:39,  4.05it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 51%|█████     | 165/323 [00:47<00:40,  3.86it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 51%|█████▏    | 166/323 [00:47<00:42,  3.73it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 52%|█████▏    | 167/323 [00:47<00:41,  3.77it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 52%|█████▏    | 169/323 [00:47<00:33,  4.66it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 53%|█████▎    | 171/323 [00:48<00:24,  6.25it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 53%|█████▎    | 172/323 [00:48<00:28,  5.22it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 54%|█████▍    | 174/323 [00:48<00:27,  5.45it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 54%|█████▍    | 175/323 [00:48<00:24,  5.94it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 54%|█████▍    | 176/323 [00:49<00:27,  5.32it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 55%|█████▌    | 178/323 [00:49<00:31,  4.64it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 56%|█████▌    | 180/323 [00:49<00:24,  5.94it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 57%|█████▋    | 183/323 [00:50<00:21,  6.57it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 57%|█████▋    | 184/323 [00:50<00:20,  6.74it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 57%|█████▋    | 185/323 [00:50<00:24,  5.63it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 58%|█████▊    | 186/323 [00:50<00:25,  5.33it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 58%|█████▊    | 187/323 [00:51<00:34,  3.92it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 59%|█████▊    | 189/323 [00:51<00:30,  4.40it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 59%|█████▉    | 191/323 [00:52<00:24,  5.28it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 60%|█████▉    | 193/323 [00:52<00:19,  6.75it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 60%|██████    | 194/323 [00:52<00:18,  6.85it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 61%|██████    | 196/323 [00:52<00:21,  5.83it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 61%|██████▏   | 198/323 [00:53<00:19,  6.30it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 62%|██████▏   | 199/323 [00:53<00:19,  6.28it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 62%|██████▏   | 200/323 [00:53<00:23,  5.15it/s]

BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 62%|██████▏   | 201/323 [00:53<00:21,  5.81it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 63%|██████▎   | 202/323 [00:53<00:21,  5.51it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 63%|██████▎   | 203/323 [00:54<00:22,  5.22it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 63%|██████▎   | 205/323 [00:54<00:20,  5.69it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 64%|██████▍   | 206/323 [00:54<00:21,  5.49it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 64%|██████▍   | 207/323 [00:55<00:25,  4.46it/s]/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 64%|██████▍   | 208/323 [00:55<00:29,  3.87it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 65%|██████▍   | 209/323 [00:55<00:33,  3.41it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 65%|██████▌   | 210/323 [00:56<00:38,  2.97it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 65%|██████▌   | 211/323 [00:56<00:35,  3.18it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 66%|██████▋   | 214/323 [00:57<00:25,  4.21it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 67%|██████▋   | 216/323 [00:57<00:20,  5.22it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 67%|██████▋   | 217/323 [00:57<00:20,  5.14it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 68%|██████▊   | 219/323 [00:57<00:19,  5.42it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 68%|██████▊   | 220/323 [00:58<00:22,  4.52it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


/var/folders/cr/n708zkvn3yl95rky5npx_kzw0000gn/T/ipykernel_93337/3787582379.py:49: RuntimeWarning: invalid value encountered in divide
  all_sparse_scores = (all_sparse_scores - all_sparse_scores.min()) / (all_sparse_scores.max() - all_sparse_scores.min())
 68%|██████▊   | 221/323 [00:58<00:24,  4.12it/s]

All sparse scores are the same.
[0. 0. 0. 0. 0.]
BM25 Scores: [nan nan nan ... nan nan nan]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 69%|██████▉   | 224/323 [00:59<00:22,  4.46it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 70%|██████▉   | 225/323 [00:59<00:25,  3.82it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 70%|██████▉   | 226/323 [00:59<00:27,  3.49it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 71%|███████   | 228/323 [01:00<00:25,  3.67it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 71%|███████   | 229/323 [01:00<00:27,  3.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 72%|███████▏  | 231/323 [01:01<00:23,  3.91it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 72%|███████▏  | 233/323 [01:01<00:20,  4.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 73%|███████▎  | 235/323 [01:01<00:20,  4.31it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 73%|███████▎  | 237/323 [01:02<00:26,  3.25it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 74%|███████▎  | 238/323 [01:03<00:26,  3.26it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 74%|███████▍  | 239/323 [01:03<00:32,  2.62it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 74%|███████▍  | 240/323 [01:03<00:31,  2.61it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 75%|███████▍  | 241/323 [01:04<00:34,  2.41it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 75%|███████▍  | 242/323 [01:04<00:31,  2.59it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 75%|███████▌  | 243/323 [01:05<00:29,  2.68it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 76%|███████▌  | 245/323 [01:05<00:23,  3.38it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 76%|███████▌  | 246/323 [01:05<00:21,  3.57it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 76%|███████▋  | 247/323 [01:06<00:21,  3.49it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 77%|███████▋  | 250/323 [01:06<00:17,  4.21it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 78%|███████▊  | 252/323 [01:07<00:14,  4.89it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 78%|███████▊  | 253/323 [01:07<00:13,  5.15it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 79%|███████▊  | 254/323 [01:07<00:13,  5.26it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 79%|███████▉  | 255/323 [01:07<00:17,  3.94it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [1. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 80%|███████▉  | 257/323 [01:08<00:17,  3.85it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 80%|████████  | 259/323 [01:08<00:14,  4.36it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 81%|████████  | 261/323 [01:09<00:16,  3.73it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 81%|████████  | 262/323 [01:09<00:17,  3.40it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 81%|████████▏ | 263/323 [01:10<00:19,  3.12it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 82%|████████▏ | 264/323 [01:10<00:20,  2.95it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 82%|████████▏ | 265/323 [01:10<00:18,  3.05it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 83%|████████▎ | 267/323 [01:11<00:19,  2.90it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 83%|████████▎ | 269/323 [01:12<00:15,  3.45it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 84%|████████▍ | 271/323 [01:12<00:15,  3.25it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 84%|████████▍ | 272/323 [01:13<00:17,  2.97it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 85%|████████▍ | 273/323 [01:13<00:18,  2.64it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 85%|████████▍ | 274/323 [01:13<00:18,  2.67it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 85%|████████▌ | 275/323 [01:14<00:19,  2.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 85%|████████▌ | 276/323 [01:14<00:19,  2.46it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 86%|████████▌ | 277/323 [01:15<00:16,  2.71it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 86%|████████▌ | 278/323 [01:15<00:15,  2.85it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 86%|████████▋ | 279/323 [01:15<00:16,  2.60it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 87%|████████▋ | 280/323 [01:16<00:16,  2.58it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 87%|████████▋ | 281/323 [01:16<00:15,  2.70it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 87%|████████▋ | 282/323 [01:16<00:16,  2.55it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 88%|████████▊ | 284/323 [01:17<00:12,  3.25it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 88%|████████▊ | 285/323 [01:17<00:11,  3.30it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 89%|████████▊ | 286/323 [01:18<00:13,  2.78it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 89%|████████▉ | 287/323 [01:18<00:11,  3.16it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 89%|████████▉ | 289/323 [01:19<00:12,  2.79it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 90%|████████▉ | 290/323 [01:19<00:13,  2.45it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 90%|█████████ | 291/323 [01:20<00:12,  2.48it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 90%|█████████ | 292/323 [01:20<00:11,  2.72it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 91%|█████████ | 293/323 [01:20<00:10,  2.76it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 91%|█████████▏| 295/323 [01:21<00:08,  3.37it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 92%|█████████▏| 298/323 [01:21<00:05,  4.35it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 93%|█████████▎| 300/323 [01:22<00:04,  5.36it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 94%|█████████▍| 303/323 [01:22<00:03,  6.63it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 94%|█████████▍| 304/323 [01:22<00:03,  6.17it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 94%|█████████▍| 305/323 [01:23<00:05,  3.21it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 95%|█████████▍| 306/323 [01:23<00:05,  3.13it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 95%|█████████▌| 308/323 [01:24<00:04,  3.09it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 96%|█████████▌| 310/323 [01:25<00:04,  2.93it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 96%|█████████▋| 311/323 [01:25<00:04,  2.48it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 97%|█████████▋| 312/323 [01:25<00:04,  2.62it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 97%|█████████▋| 313/323 [01:26<00:03,  2.98it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 97%|█████████▋| 314/323 [01:26<00:02,  3.20it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 98%|█████████▊| 315/323 [01:26<00:02,  2.99it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 98%|█████████▊| 316/323 [01:27<00:02,  3.01it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 98%|█████████▊| 317/323 [01:27<00:01,  3.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 99%|█████████▉| 319/323 [01:27<00:00,  4.44it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]
BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


 99%|█████████▉| 321/323 [01:28<00:00,  4.55it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


100%|█████████▉| 322/323 [01:28<00:00,  3.98it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


100%|██████████| 323/323 [01:28<00:00,  3.64it/s]

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


In [21]:
run_sparse = prepare_run_data(results["sparse"])
run_dense = prepare_run_data(results["dense"])
run_rank_fusion = prepare_run_data(results["rank_fusion"])
run_cascade = prepare_run_data(results["cascade"])

# Evaluate results with pytrec_eval
evaluator = pytrec_eval.RelevanceEvaluator(qrels_dict, {'recall.5', 'ndcg_cut.5'})
eval_results_sparse = evaluator.evaluate(run_sparse)
eval_results_dense = evaluator.evaluate(run_dense)
eval_results_rank_fusion = evaluator.evaluate(run_rank_fusion)
eval_results_cascade = evaluator.evaluate(run_cascade)

# Aggregate metrics for overall performance
aggregated_results = {
    "sparse": {
        metric: sum([res[metric] for res in eval_results_sparse.values()]) / len(eval_results_sparse)
        for metric in eval_results_sparse[next(iter(eval_results_sparse))]
    },
    "dense": {
        metric: sum([res[metric] for res in eval_results_dense.values()]) / len(eval_results_dense)
        for metric in eval_results_dense[next(iter(eval_results_dense))]
    },
    "rank_fusion": {
        metric: sum([res[metric] for res in eval_results_rank_fusion.values()]) / len(eval_results_rank_fusion)
        for metric in eval_results_rank_fusion[next(iter(eval_results_rank_fusion))]
    },
    "cascade": {
        metric: sum([res[metric] for res in eval_results_cascade.values()]) / len(eval_results_cascade)
        for metric in eval_results_cascade[next(iter(eval_results_cascade))]
    }
}

print("Aggregated results:", json.dumps(aggregated_results, indent=4))
print("Retrieval results and metrics saved to files.")

Aggregated results: {
    "sparse": {
        "recall_5": 0.07827800125225781,
        "ndcg_cut_5": 0.2371057696379276
    },
    "dense": {
        "recall_5": 0.11426360036775385,
        "ndcg_cut_5": 0.3420563224664553
    },
    "rank_fusion": {
        "recall_5": 0.10960074602054531,
        "ndcg_cut_5": 0.3217791666948595
    },
    "cascade": {
        "recall_5": 0.07827800125225781,
        "ndcg_cut_5": 0.2371057696379276
    }
}
Retrieval results and metrics saved to files.


# Section 4: QA with Language Model

In [22]:
# QA for the first query
QUERY_INDEX = 3                                                     # Index of the query to be used for retrieval
query = all_queries[QUERY_INDEX - 1]                                # Select the query from the list based on the index
query_text = query['title'] if isinstance(query, dict) else query   # Get the query text

# Retrieval calls:

# Perform dense retrieval using query embedding and document embeddings
dense_top_k_indices, dense_top_k_scores = dense_retrieve(query_embeddings[QUERY_INDEX], doc_embeddings)
# Perform sparse retrieval using BM25 on the query text
sparse_top_k_indices, sparse_top_k_scores = bm25_retrieve(query_text, bm25)
# Perform rank fusion retrieval by combining BM25 and dense retrieval results
rank_top_k_indices, rank_top_k_scores = fusion_retrieve(
    query_embeddings[QUERY_INDEX],
    doc_embeddings,
    query_text
)
# Perform cascading retrieval: first BM25, then re-rank with dense retrieval
cascading_top_k_indices, cascading_top_k_scores = cascade_retrieve(
    query_embeddings[QUERY_INDEX],
    doc_embeddings,
    query_text
)

# Get retrieved documents for each method
dense_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(dense_top_k_indices)]
sparse_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(sparse_top_k_indices)]
rank_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(rank_top_k_indices)]
cascading_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(cascading_top_k_indices)]

# Definition of the model that will be used to generate the various responses.
lm_pipeline = pipeline("text-generation",
                      model="meta-llama/Llama-3.2-1B",
                      device=0 if device == "cuda" else -1)

BM25 Scores: [0. 0. 0. ... 0. 0. 0.]
Dense Scores: [0. 0. 0. ... 0. 0. 0.]


ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 32.0, 'high_freq_factor': 4.0, 'low_freq_factor': 1.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}

#### Question-answering using DENSE RETRIEVAL

In [ ]:
print("------------------ DENSE RETRIEVAL ----------------------\n")
context = "\n".join(dense_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]
response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()

print(f"------------------ Response ------------------\n{response}")

#### Question-answering using SPARSE RETRIEVAL

In [ ]:
print("------------------ SPARSE RETRIEVAL ----------------------\n")
context = "\n".join(sparse_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

#### Question-answering using RANK FUSION

In [ ]:
print("------------------ RANK FUSION ----------------------\n")
context = "\n".join(rank_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

#### Question-answering using CASCADING RETRIEVAL

In [ ]:
print("------------------ CASCADING RETRIEVAL ----------------------\n")
context = "\n".join(cascading_retrieved_docs)
prompt = f"Context:\n{context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

# Generate response
response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

#### Question-answering WITH NO CONTEXT PROVIDED WITH RAG

In [ ]:

print("------------------ RESPONSE WITHOUT RAG ----------------------\n")
prompt = f"""Question:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"""

print(f"----------------- Length of the prompt -----------------\n{len(prompt.split())} words")
print(f"------------------------ Prompt ------------------------\n{prompt}")

response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.7,
                      truncation=False)[0]["generated_text"]

response = response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
print(f"------------------ Response ------------------\n{response}")

In [ ]:
import random

picked_queries = random.sample(all_queries, 5)

for q in picked_queries:

    # For each query, retrieve and rank documents independently
    query_text = q['title']
    cascading_top_k_indices, cascading_top_k_scores = cascade_retrieve(query_embeddings[QUERY_INDEX], doc_embeddings, query_text)

    # Use the top-k documents for that specific query
    cascading_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(cascading_top_k_indices)]
    cascading_context = "\n".join(cascading_retrieved_docs)

    # Repeat the process for rank fusion
    rank_top_k_indices, rank_top_k_scores = fusion_retrieve(query_embeddings[QUERY_INDEX], doc_embeddings, query_text)
    rank_retrieved_docs = [f"Document {i+1}: {all_docs[idx]['abstract']}" for i, idx in enumerate(rank_top_k_indices)]
    rank_fusion_context = "\n".join(rank_retrieved_docs)


    cascading_prompt = f"Context:\n{cascading_context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"
    rank_fusion_prompt = f"Context:\n{rank_fusion_context}\n\nQuestion:\n{query_text}\n\nAnswer in a concise and clear manner without repetition (if no direct answer, provide a general summary):"

    # Generate response using language model
    cascading_response = lm_pipeline(cascading_prompt,
                           max_new_tokens=150,
                           temperature=0.7,
                           truncation=False)[0]["generated_text"]

    rank_fusion_response = lm_pipeline(prompt,
                      max_new_tokens=150,
                      temperature=0.1,
                      truncation=False)[0]["generated_text"]

    # Extract the answer from the response
    cascading_response = cascading_response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()
    rank_fusion_response = rank_fusion_response.split("Answer in a concise and clear manner without repetition (if no direct answer, provide a general summary):")[1].strip()

    # Print the results
    print(f"\nQuery: {query_text}")
    print(f"Cascading Response: {cascading_response}")
    print(f"Rank Fusion Response: {rank_fusion_response}")
    print("------------------------------\n")
